name: trigger-dev-pipeline
on: 
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
jobs:
  dispatch-event:
    name: "dev deployment event"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: "make scripts executable"
      run: chmod +x ./ci-scripts/*

    - name: "set PR number"
      run: echo "::set-env name=PR_number::`echo $GITHUB_REF | cut -f 3 -d /`"

    - name: "install python dependencies"
      run: pip install requests

    - name: "set branch owner"
      run: echo "::set-env name=branch_owner::`./ci-scripts/get_branch_owner.py $PR_number`"

    - name: "set branch name"
      run: echo "::set-env name=branch_name::`echo ${{github.head_ref}}`"

    - name: "Notify PR Event to CrownOps"
      run: |
          curl -X POST https://api.github.com/repos/netgroup-polito/CrownOps/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.CI_TOKEN }} \
          --data '{"event_type": "dev-event", "client_payload": { "actor": "'"$branch_owner"'", "ref": "'"$branch_name"'" }}'
      if: github.ref != 'refs/heads/master'
