name: Release a new CrownLabs version
on:
  push:
    tags:
      - '**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Get the CrownLabs version
        id: version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push the Frontend image
        uses: docker/build-push-action@v2
        with:
          tags: |
            crownlabs/website:latest
            crownlabs/website:stable
            crownlabs/website:${{ steps.version.outputs.version }}
          push: true
          file: ./webservice/Dockerfile
          context: ./webservice

      - name: Build and Push the Laboratory operator image
        uses: docker/build-push-action@v2
        with:
          tags: |
            crownlabs/laboratory-operator:latest
            crownlabs/laboratory-operator:stable
            crownlabs/laboratory-operator:${{ steps.version.outputs.version }}
          push: true
          file: ./operators/labInstance-operator/Dockerfile
          context: ./operators/labInstance-operator/

      - name: Notify Event to CrownOps
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
          repository: netgroup-polito/CrownOps
          event-type: release-event
          client_payload: '{"version": "${{ steps.version.outputs.version }}"}'